"""empty message

Revision ID: 52457ba86866
Revises: 
Create Date: 2018-09-28 18:35:10.821700

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '52457ba86866'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('circuit',
    sa.Column('circuitId', sa.Integer(), nullable=False),
    sa.Column('circuitRef', sa.String(length=255), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('location', sa.String(length=255), nullable=True),
    sa.Column('country', sa.String(length=255), nullable=True),
    sa.Column('lat', sa.Float(), nullable=True),
    sa.Column('lng', sa.Float(), nullable=True),
    sa.Column('alt', sa.Integer(), nullable=True),
    sa.Column('url', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('circuitId')
    )
    op.create_table('driver',
    sa.Column('driverId', sa.Integer(), nullable=False),
    sa.Column('driverRef', sa.Integer(), nullable=True),
    sa.Column('number', sa.Integer(), nullable=True),
    sa.Column('code', sa.Float(), nullable=True),
    sa.Column('forename', sa.Integer(), nullable=True),
    sa.Column('surname', sa.String(length=255), nullable=True),
    sa.Column('dob', sa.Integer(), nullable=True),
    sa.Column('nationality', sa.String(length=255), nullable=True),
    sa.Column('url', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('driverId')
    )
    op.create_table('driver_standing',
    sa.Column('driverStandingsId', sa.Integer(), nullable=False),
    sa.Column('raceId', sa.Integer(), nullable=True),
    sa.Column('driverId', sa.Integer(), nullable=True),
    sa.Column('points', sa.Float(), nullable=True),
    sa.Column('position', sa.Integer(), nullable=True),
    sa.Column('positionText', sa.String(length=255), nullable=True),
    sa.Column('wins', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('driverStandingsId')
    )
    op.create_table('qualifying',
    sa.Column('qualifyId', sa.Integer(), nullable=False),
    sa.Column('raceId', sa.Integer(), nullable=True),
    sa.Column('driverId', sa.Integer(), nullable=True),
    sa.Column('constructorId', sa.Integer(), nullable=True),
    sa.Column('number', sa.Integer(), nullable=True),
    sa.Column('position', sa.Integer(), nullable=True),
    sa.Column('q1', sa.String(length=255), nullable=True),
    sa.Column('q2', sa.String(length=255), nullable=True),
    sa.Column('q3', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('qualifyId')
    )
    op.create_table('race',
    sa.Column('raceId', sa.Integer(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=True),
    sa.Column('round', sa.Integer(), nullable=True),
    sa.Column('circuitId', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('date', sa.Date(), nullable=True),
    sa.Column('time', sa.Time(), nullable=True),
    sa.Column('url', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('raceId')
    )
    op.create_table('result',
    sa.Column('resultId', sa.Integer(), nullable=False),
    sa.Column('raceId', sa.Integer(), nullable=False),
    sa.Column('driverId', sa.Integer(), nullable=False),
    sa.Column('constructorId', sa.Integer(), nullable=False),
    sa.Column('number', sa.Integer(), nullable=True),
    sa.Column('grid', sa.Integer(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=True),
    sa.Column('positionText', sa.String(length=255), nullable=False),
    sa.Column('positionOrder', sa.Integer(), nullable=False),
    sa.Column('points', sa.Integer(), nullable=False),
    sa.Column('laps', sa.Integer(), nullable=False),
    sa.Column('time', sa.String(length=255), nullable=True),
    sa.Column('milliseconds', sa.Integer(), nullable=True),
    sa.Column('fastestLap', sa.Integer(), nullable=True),
    sa.Column('rank', sa.Integer(), nullable=True),
    sa.Column('fastestLapTime', sa.String(length=255), nullable=True),
    sa.Column('fastestLapSpeed', sa.String(length=255), nullable=True),
    sa.Column('statusId', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('resultId')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('result')
    op.drop_table('race')
    op.drop_table('qualifying')
    op.drop_table('driver_standing')
    op.drop_table('driver')
    op.drop_table('circuit')
    # ### end Alembic commands ###
